site_name: "D&D: Glimbourne"

theme:
  name: 'material'
  palette:

  # Light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: pink
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode

  # Dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: pink
    accent: blue
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.prune
    - toc.follow

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.snippets

  - toc:
      toc_depth: 3

plugins:
  - search
  - awesome-pages
  - roamlinks

extra:
  generator: false
  homepage: https://requiae.github.io/glimbourne/

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
